# Generated by Django 5.2.4 on 2025-07-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanrequest",
            name="data_esito",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loanrequest",
            name="user_carta_identita",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="loanrequest",
            name="user_citta",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="loanrequest",
            name="user_cognome",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="loanrequest",
            name="user_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="loanrequest",
            name="user_nome",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="loanrequest",
            name="user_telefono",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="loanrequest",
            name="user_via",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
